CREATE TABLE pets (
    pet_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    level INTEGER NOT NULL,
    exp INTEGER NOT NULL,
    stage VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE members (
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    nickname VARCHAR(30) NOT NULL,
    role VARCHAR(20) NOT NULL,
    pet_id BIGINT UNIQUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_members_email UNIQUE (email),
    CONSTRAINT fk_members_to_pets FOREIGN KEY (pet_id) REFERENCES pets (pet_id)
);

CREATE TABLE memos (
    memo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    is_parsed BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_memos_to_members FOREIGN KEY (member_id) REFERENCES members (member_id)
);

CREATE INDEX idx_memos_member_created ON memos (member_id, created_at);

CREATE TABLE memo_analyses (
    memo_analysis_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL,
    memo_id BIGINT NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL,
    schedule_candidate BOOLEAN NOT NULL,
    title VARCHAR(100),
    scheduled_at DATE,
    scheduled_time TIME(0),
    location VARCHAR(100),
    summary_info TEXT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_memo_analyses_to_memos FOREIGN KEY (memo_id) REFERENCES memos (memo_id)
);

CREATE TABLE schedules (
    schedule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    memo_id BIGINT,
    title VARCHAR(100) NOT NULL,
    scheduled_at DATE NOT NULL,
    scheduled_time TIME(0),
    location VARCHAR(100),
    summary_info TEXT,
    is_completed BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_schedules_to_members FOREIGN KEY (member_id) REFERENCES members (member_id),
    CONSTRAINT fk_schedules_to_memos FOREIGN KEY (memo_id) REFERENCES memos (memo_id)
);

CREATE INDEX idx_schedules_member_date ON schedules (member_id, scheduled_at);

CREATE TABLE quests (
    quest_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    category VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    reward_exp INTEGER NOT NULL,
    started_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_quests_to_members FOREIGN KEY (member_id) REFERENCES members (member_id)
);

CREATE INDEX idx_quests_member_status ON quests (member_id, status);
